<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FrameViewAnalyzer.Core\FrameViewAnalyzer.Core.csproj" />
    <ProjectReference Include="..\FrameViewAnalyzer.Analytics\FrameViewAnalyzer.Analytics.csproj" />
    <ProjectReference Include="..\FrameViewAnalyzer.Infrastructure\FrameViewAnalyzer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>assets\frameview-analyzer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\frameview-analyzer.png" />
    <Resource Include="assets\frameview-analyzer.ico" />
  </ItemGroup>

</Project>
